# Generated by Django 3.1.5 on 2021-02-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncresults',
            name='created_on',
            field=models.DateTimeField(db_index=True, editable=False, verbose_name='created_on'),
        ),
    ]
