# Generated by Django 3.1.5 on 2021-02-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20210201_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncresults',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created_on'),
        ),
    ]
